# Generated by Django 4.2.1 on 2023-05-13 03:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lf_Cargos',
            fields=[
                ('ch_key', models.AutoField(primary_key=True, serialize=False)),
                ('ch_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'lf_cargos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lf_Certificados',
            fields=[
                ('cer_key', models.AutoField(primary_key=True, serialize=False)),
                ('cer_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'lf_certificados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lf_Employees',
            fields=[
                ('emp_key', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(blank=True, max_length=70, null=True)),
                ('emp_email', models.CharField(blank=True, max_length=80, null=True)),
                ('emp_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_fk_ch_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lf_cargos')),
            ],
            options={
                'db_table': 'lf_employees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lf_Projects',
            fields=[
                ('pr_key', models.AutoField(primary_key=True, serialize=False)),
                ('pr_desc', models.CharField(blank=True, max_length=150, null=True)),
                ('pr_address', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'lf_projects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lf_Reportes',
            fields=[
                ('rep_key', models.AutoField(primary_key=True, serialize=False)),
                ('rep_name', models.CharField(blank=True, max_length=80, null=True)),
                ('rep_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('rep_user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rep_send', models.IntegerField(blank=True, null=True)),
                ('rep_send_email', models.CharField(blank=True, max_length=80, null=True)),
                ('rep_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('rep_yyyymmdd', models.CharField(default=datetime.date(2023, 5, 12), max_length=45)),
                ('rep_ws_to', models.CharField(blank=True, max_length=255, null=True)),
                ('rep_pages', models.IntegerField(blank=True, null=True)),
                ('rep_fk_emp_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_fk_emp_key', to='main.lf_employees')),
                ('rep_fk_emp_key_sup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_fk_emp_key_sup', to='main.lf_employees', verbose_name='emp_name')),
                ('rep_fk_pr_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_fk_emp_key', to='main.lf_projects')),
            ],
            options={
                'db_table': 'lf_reportes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lf_RepEmails',
            fields=[
                ('repe_key', models.AutoField(primary_key=True, serialize=False)),
                ('repe_fk_emp_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.lf_employees')),
                ('repe_fk_rep_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.lf_reportes')),
            ],
            options={
                'db_table': 'lf_rep_emails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lf_Photos2',
            fields=[
                ('ph_key2', models.AutoField(primary_key=True, serialize=False)),
                ('ph_fk_ph_key', models.IntegerField(blank=True, null=True)),
                ('ph_link2', models.FileField(blank=True, null=True, upload_to='img2/')),
                ('ph_yyyymmdd', models.CharField(default=datetime.date(2023, 5, 12), max_length=45)),
                ('ph_desc2', models.CharField(blank=True, max_length=254, null=True)),
                ('ph_fk_rep_key2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lf_reportes')),
            ],
            options={
                'db_table': 'lf_photos2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lf_Photos',
            fields=[
                ('ph_key', models.AutoField(primary_key=True, serialize=False)),
                ('ph_link', models.FileField(blank=True, null=True, upload_to='img/')),
                ('ph_yyyymmdd', models.CharField(default=datetime.date(2023, 5, 12), max_length=45)),
                ('ph_desc', models.CharField(blank=True, max_length=5000, null=True)),
                ('ph_user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ph_obs', models.CharField(blank=True, max_length=5000, null=True)),
                ('ph_fk_rep_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lf_reportes')),
            ],
            options={
                'db_table': 'lf_photos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lf_EmpCer',
            fields=[
                ('ec_key', models.AutoField(primary_key=True, serialize=False)),
                ('ec_exp_yyyymmdd', models.CharField(default=datetime.date(2023, 5, 12), max_length=45)),
                ('ec_fk_cer_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.lf_certificados')),
                ('ec_fk_emp_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.lf_employees')),
            ],
            options={
                'db_table': 'lf_emp_cer',
                'managed': True,
            },
        ),
    ]
