# Generated by Django 4.2.1 on 2023-05-13 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lf_empcer',
            name='ec_exp_yyyymmdd',
            field=models.CharField(default=datetime.date(2023, 5, 13), max_length=45),
        ),
        migrations.AlterField(
            model_name='lf_photos',
            name='ph_yyyymmdd',
            field=models.CharField(default=datetime.date(2023, 5, 13), max_length=45),
        ),
        migrations.AlterField(
            model_name='lf_photos2',
            name='ph_yyyymmdd',
            field=models.CharField(default=datetime.date(2023, 5, 13), max_length=45),
        ),
        migrations.AlterField(
            model_name='lf_reportes',
            name='rep_yyyymmdd',
            field=models.CharField(default=datetime.date(2023, 5, 13), max_length=45),
        ),
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(to='main.lf_employees')),
            ],
        ),
    ]
