# Generated by Django 4.1.3 on 2022-12-04 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lf_photos',
            name='ph_fk_rep_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lf_reportes'),
        ),
    ]
