# Generated by Django 4.2.1 on 2023-05-07 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lf_photos_ph_fk_rep_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lf_empcer',
            name='ec_exp_yyyymmdd',
            field=models.CharField(default=datetime.date(2023, 5, 7), max_length=45),
        ),
        migrations.AlterField(
            model_name='lf_photos',
            name='ph_yyyymmdd',
            field=models.CharField(default=datetime.date(2023, 5, 7), max_length=45),
        ),
        migrations.AlterField(
            model_name='lf_photos2',
            name='ph_yyyymmdd',
            field=models.CharField(default=datetime.date(2023, 5, 7), max_length=45),
        ),
        migrations.AlterField(
            model_name='lf_reportes',
            name='rep_yyyymmdd',
            field=models.CharField(default=datetime.date(2023, 5, 7), max_length=45),
        ),
    ]
