# Generated by Django 4.2.1 on 2023-05-13 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lf_empcer_ec_exp_yyyymmdd_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailGroup',
        ),
    ]
